CREATE TABLE vacancies (
    id bigserial PRIMARY KEY,
    premium BOOL,
    name VARCHAR,
    department VARCHAR,
    has_test BOOL,
    response_letter_required BOOL,
    area_id SERIAL,
    area_name varchar,
    salary_from SERIAL,
    salary_to SERIAL,
    salary_currency varchar,
    salary_gross BOOL,
    type_id varchar,
    type_name varchar,
    address varchar,
    response_url varchar,
    sort_point_distance varchar,
    employer_id serial,
    employer_name varchar,
    employer_url varchar,
    employer_alternate_url varchar,
    employer_logo_urls_original varchar,
    employer_logo_urls_90 varchar,
    employer_logo_urls_240 varchar,
    employer_vacancies_url varchar,
    employer_trusted bool,
    published_at timestamp,
    created_at timestamp,
    archived bool,
    apply_alternate_url varchar,
    insider_interview varchar,
    url varchar,
    alternate_url varchar,
    relations jsonb,
    snippet_requirement varchar,
    snippet_responsibility varchar,
    contacts jsonb,
    schedule_id varchar,
    schedule_name varchar
)
-- DROP TABLE details

